---
title: "Pacific Barracuda Stochastic size limit sims"
output: pdf_document
date: "2022-12-06"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1. Extract dataframe of LH parameters and FM
```{r}
LHBarracuda <- (Ex.Spp.LBSPR.LinfMK_Barracuda1[["LH_inputs"]])
LHBarracuda$FM <- Ex.Spp.LBSPR.LinfMK_Barracuda1[["F_M"]]


```

#28 INCH MSL knife edge
```{r}
LHBarracuda$SPR_28_Inch_MSL_KE <- NA


  for(i in 1:nrow(LHBarracuda)){
   if(is.na(LHBarracuda$FM[i])){
    LHBarracuda$SPR_28_Inch_MSL_KE[i] <- NA }
else{
  
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Pacfic Barracuda"

KBPars@Linf <- LHBarracuda$Linf[i]
KBPars@L50 <- LHBarracuda$L50[i]
KBPars@L95 <- LHBarracuda$L95[i]
KBPars@MK <- LHBarracuda$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 711
KBPars@SL95 <- 712
KBPars@BinWidth <- 20 
KBPars@FM <- LHBarracuda$FM[i]
KBPars@BinMax <- 2000
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_Barracuda_28_KE <- LBSPRsim(KBPars)

LHBarracuda$SPR_28_Inch_MSL_KE[i] <- MySim_Barracuda_28_KE@SPR
}}


#####
quantile(LHBarracuda$SPR_28_Inch_MSL_KE, probs = c(0.025,0.25,0.5,0.75,0.975), na.rm = T) #median SPR = 0.6078366

###########

```

#26 INCH MSL knife edge
```{r}
LHBarracuda$SPR_26_Inch_MSL_KE <- NA



  for(i in 1:nrow(LHBarracuda)){
  if(is.na(LHBarracuda$FM[i])){
    LHBarracuda$SPR_26_Inch_MSL_KE[i] <- NA }
else{
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Pacfic Barracuda"

KBPars@Linf <- LHBarracuda$Linf[i]
KBPars@L50 <- LHBarracuda$L50[i]
KBPars@L95 <- LHBarracuda$L95[i]
KBPars@MK <- LHBarracuda$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 660
KBPars@SL95 <- 661
KBPars@BinWidth <- 20 
KBPars@FM <- LHBarracuda$FM[i]
KBPars@BinMax <- 2000
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_Barracuda_26_KE <- LBSPRsim(KBPars)


LHBarracuda$SPR_26_Inch_MSL_KE[i] <- MySim_Barracuda_26_KE@SPR

}}


###
quantile(LHBarracuda$SPR_26_Inch_MSL_KE, probs = c(0.025,0.25,0.5,0.75,0.975), na.rm = T) #median SPR = 0.5139154

###########

```

#manipulate dataframe
```{r}
Barracuda_sizelimits <- data.frame(cbind(Ex.Spp.LBSPR.LinfMK_Barracuda1$SPR, LHBarracuda$SPR_28_Inch_MSL_KE, LHBarracuda$SPR_26_Inch_MSL_KE))
colnames(Barracuda_sizelimits) <- c("2004-2021 CRFS", "28-Inch MSL Simulation (Knife-Edge Selectivity)", "26-Inch MSL Simulation (Knife-Edge Selectivity)")
Barracuda_sizelimits_gg<-melt(Barracuda_sizelimits,variable.name="Data",value.name="SPR")
colnames(Barracuda_sizelimits_gg)<-c("Scenario","SPR")



#VIOLIN
ggplot(Barracuda_sizelimits_gg,aes(Scenario,SPR, group=Scenario)) +
  scale_color_manual(values=c("black", "red")) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) +
annotation_custom(grob = green, xmin = -Inf, xmax = Inf, ymin = .5, ymax = 1)+
  annotation_custom(grob = green_yellow, xmin = -Inf, xmax = Inf, ymin = .3, ymax = .6)+
  annotation_custom(grob = yellow, xmin = -Inf, xmax = Inf, ymin = .25, ymax = .3)+
  annotation_custom(grob = yellow_red, xmin = -Inf, xmax = Inf, ymin = 0, ymax = .25)+
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75))+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=1.25)+
  geom_text(aes(1.4, .20 ,label = "20% SPR", vjust = -1))+ #label horizontal line at 20% SPR
  geom_text(aes(1.4, .40 ,label = "40% SPR", vjust = -1))+ #label horizontal line at 40% SPR
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("Pacific Barracuda Size Limit Simulations")+
  theme(plot.title=element_text(hjust=0.5))+
scale_x_discrete(limits = c("", "2004-2021 CRFS", "28-Inch MSL Simulation (Knife-Edge Selectivity)", "26-Inch MSL Simulation (Knife-Edge Selectivity)", ""), breaks = c("2004-2021 CRFS", "28-Inch MSL Simulation (Knife-Edge Selectivity)", "26-Inch MSL Simulation (Knife-Edge Selectivity)"), expand=c(0,0), labels = label_wrap(15))
  
#ggsave("Barracuda_Stochastic_MSLsim.png", width = 30, height = 20, units = "cm", dpi = 500)
```



