---
title: "Olive Rockfish Stochastic Size Limit Simulations"
output: pdf_document
date: "2022-12-07"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1. Extract dataframe of LH parameters and FM
```{r}
LHOliveRFCV1 <- (Ex.Spp.LBSPR.LinfMK_Olive1[["LH_inputs"]])
LHOliveRFCV1$FM <- (Ex.Spp.LBSPR.LinfMK_Olive1[["F_M"]])


```

#12 INCH MSL knife edge
```{r}
LHOliveRFCV1$SPR_12_Inch_MSL_KE <- NA


  for(i in 1:nrow(LHOliveRFCV1)){
   if(is.na(LHOliveRFCV1$FM[i])){
    LHOliveRFCV1$SPR_12_Inch_MSL_KE[i] <- NA }
else{
  
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- LHOliveRFCV1$Linf[i]
KBPars@L50 <- LHOliveRFCV1$L50[i]
KBPars@L95 <- LHOliveRFCV1$L95[i]
KBPars@MK <- LHOliveRFCV1$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 305
KBPars@SL95 <- 306
KBPars@BinWidth <- 10
KBPars@FM <- LHOliveRFCV1$FM[i]
KBPars@BinMax <- 700
KBPars@BinMin <- 0
KBPars@L_units <- "mm"
KBPars@CVLinf <- .1

MySim_Olive_12_KE <- LBSPRsim(KBPars)

LHOliveRFCV1$SPR_12_Inch_MSL_KE[i] <- MySim_Olive_12_KE@SPR
}}


#####
quantile(LHOliveRFCV1$SPR_12_Inch_MSL_KE, probs = c(0.025,0.25,0.5,0.75,0.975), na.rm = T) #median SPR = 0.45489731

quantile(LHOliveRFCV1$FM, probs = c(0.025,0.25,0.5,0.75,0.975), na.rm = T) #.920
###########

```

#14 INCH MSL knife edge
```{r}
LHOliveRFCV1$SPR_14_Inch_MSL_KE <- NA


  for(i in 1:nrow(LHOliveRFCV1)){
   if(is.na(LHOliveRFCV1$FM[i])){
    LHOliveRFCV1$SPR_14_Inch_MSL_KE[i] <- NA }
else{
  
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- LHOliveRFCV1$Linf[i]
KBPars@L50 <- LHOliveRFCV1$L50[i]
KBPars@L95 <- LHOliveRFCV1$L95[i]
KBPars@MK <- LHOliveRFCV1$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 356
KBPars@SL95 <- 357
KBPars@BinWidth <- 10
KBPars@FM <- LHOliveRFCV1$FM[i]
KBPars@BinMax <- 700
KBPars@BinMin <- 0
KBPars@L_units <- "mm"
KBPars@CVLinf <- .1

MySim_Olive_14_KE <- LBSPRsim(KBPars)

LHOliveRFCV1$SPR_14_Inch_MSL_KE[i] <- MySim_Olive_14_KE@SPR
}}


#####
quantile(LHOliveRFCV1$SPR_14_Inch_MSL_KE, probs = c(0.025,0.25,0.5,0.75,0.975), na.rm = T) #median SPR = 0.5576523

quantile(LHOliveRFCV1$FM, probs = c(0.025,0.25,0.5,0.75,0.975), na.rm = T) #.920
###########

```

#16 INCH MSL knife edge
```{r}
LHOliveRFCV1$SPR_16_Inch_MSL_KE <- NA


  for(i in 1:nrow(LHOliveRFCV1)){
   if(is.na(LHOliveRFCV1$FM[i])){
    LHOliveRFCV1$SPR_16_Inch_MSL_KE[i] <- NA }
else{
  
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- LHOliveRFCV1$Linf[i]
KBPars@L50 <- LHOliveRFCV1$L50[i]
KBPars@L95 <- LHOliveRFCV1$L95[i]
KBPars@MK <- LHOliveRFCV1$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 405
KBPars@SL95 <- 406
KBPars@BinWidth <- 10
KBPars@FM <- LHOliveRFCV1$FM[i]
KBPars@BinMax <- 700
KBPars@BinMin <- 0
KBPars@L_units <- "mm"
KBPars@CVLinf <- .1

MySim_Olive_16_KE <- LBSPRsim(KBPars)

LHOliveRFCV1$SPR_16_Inch_MSL_KE[i] <- MySim_Olive_16_KE@SPR
}}


#####
quantile(LHOliveRFCV1$SPR_16_Inch_MSL_KE, probs = c(0.025,0.25,0.5,0.75,0.975), na.rm = T) #median SPR = 0.6747647 

quantile(LHOliveRFCV1$FM, probs = c(0.025,0.25,0.5,0.75,0.975), na.rm = T) #.63
###########

```

#merge data and make plot the compares figures
```{r}
OliveRF_sizelimits1 <- data.frame(cbind(Ex.Spp.LBSPR.LinfMK_Olive1$SPR, LHOliveRFCV1$SPR_12_Inch_MSL_KE,  LHOliveRFCV1$SPR_14_Inch_MSL_KE, LHOliveRFCV1$SPR_16_Inch_MSL_KE))
colnames(OliveRF_sizelimits1) <- c("2004-2021 CRFS", "12-Inch MSL Simulation", "14-Inch MSL Simulation", "16-Inch MSL Simulation")
OliveRF_sizelimits_gg1<-melt(OliveRF_sizelimits1,variable.name="Data",value.name="SPR")
colnames(OliveRF_sizelimits_gg1)<-c("Scenario","SPR")
```


```{r}

#VIOLIN
ggplot(OliveRF_sizelimits_gg1,aes(Scenario,SPR, group=Scenario)) +
  scale_color_manual(values=c("black", "red")) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) +
annotation_custom(grob = green, xmin = -Inf, xmax = Inf, ymin = .5, ymax = 1)+
  annotation_custom(grob = green_yellow, xmin = -Inf, xmax = Inf, ymin = .3, ymax = .6)+
  annotation_custom(grob = yellow, xmin = -Inf, xmax = Inf, ymin = .25, ymax = .3)+
  annotation_custom(grob = yellow_red, xmin = -Inf, xmax = Inf, ymin = 0, ymax = .25)+
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75))+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=1.25)+
  geom_text(aes(1.25, .20 ,label = "20% SPR", vjust = -1))+ #label horizontal line at 20% SPR
  geom_text(aes(1.25, .40 ,label = "40% SPR", vjust = -1))+ #label horizontal line at 40% SPR
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("Olive Rockfish Size Limit Simulations")+
  theme(plot.title=element_text(hjust=0.5))+
scale_x_discrete(limits = c("", "2004-2021 CRFS", "12-Inch MSL Simulation", "14-Inch MSL Simulation", "16-Inch MSL Simulation", ""), breaks = c("2004-2021 CRFS", "12-Inch MSL Simulation", "14-Inch MSL Simulation", "16-Inch MSL Simulation"), expand=c(0,0), labels = label_wrap(15))

#ggsave("OliveRockfish1_Stochastic_MSLsim.png", width = 30, height = 20, units = "cm", dpi = 500)
```

