---
title: "multi bsb curve"
output: pdf_document
date: "2023-02-27"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#2004-2012
```{r}
library("tidyr")

q25 <- quantile(LHSB_PRE$FM,.25, na.rm=T)
q50 <- quantile(LHSB_PRE$FM,.50, na.rm=T)
q75 <- quantile(LHSB_PRE$FM,.75, na.rm=T)
dens <- density(LHSB_PRE$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.SB2004.2012 <- ggplot()+
  #scale_color_manual(values = c("red", "blue"))+
  ggtitle("2004-2012")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHSB_PRE$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=.560, col = "black", lty = 3, lwd = .5)+ #set to median
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.15, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.15, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.0, aes(0.14, 0.01 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+ #.(-.09)
  geom_text(size = 3.0, aes(0.99, 0.01,label = "75th Percentile", vjust = 1.25), check_overlap = T)+#(+.09)
    geom_text(size = 3.0, aes(0.57, 0.01 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T) 




for(i in 1:nrow(LHSB_PRE)){
    if(is.na(LHSB_PRE$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Barred Sand Bass"

KBPars@Linf <- LHSB_PRE$Linf[i]
KBPars@L50 <- LHSB_PRE$L50[i]
KBPars@L95 <- LHSB_PRE$L95[i]
KBPars@MK <- LHSB_PRE$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 335.57 #SB_Pre_Sel50
KBPars@SL95 <- 368.52 #SB_Pre_Sel95
KBPars@BinWidth <- 10 
KBPars@FM <- LHSB_PRE$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_SandBass_2004_2012_curve <- LBSPRsim(KBPars)

curves <- calcCurves(MySim_SandBass_2004_2012_curve) #calcCurves for each set of parameter values
   
#library("dplyr")
#library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

gg.SB2004.2012 <- gg.SB2004.2012 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}
#print(gg)
```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Sand Bass"

KBPars@Linf <- 606
KBPars@L50 <- 229
KBPars@L95 <- 241.35
KBPars@MK <- 2.4
KBPars@L_units <- "mm"
KBPars@SL50 <- 335.57 #SB_Pre_Sel50
KBPars@SL95 <- 368.52 #SB_Pre_Sel95
KBPars@BinWidth <- 10 
KBPars@FM <- 0.56 #SB_Pre_FM
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_SandBass_2004_2012_curve_median <- LBSPRsim(KBPars)

SBcurves2004 <- calcCurves(MySim_SandBass_2004_2012_curve_median) #calcCurves for each set of parameter values
   
gg.SB2004.2012 <- gg.SB2004.2012 + geom_line(aes(x=SBcurves2004$FM, y=SBcurves2004$Yield), color ="darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=SBcurves2004$FM, y=SBcurves2004$SPR), color="darkred", alpha = 1, size = 1.5)

  

```
#####

2013-2021
```{r}
library("tidyr")

q25 <- quantile(LHSB_POST$FM,.25, na.rm=T)
q50 <- quantile(LHSB_POST$FM,.50, na.rm=T)
q75 <- quantile(LHSB_POST$FM,.75, na.rm=T)
dens <- density(LHSB_POST$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.SB2013.2021 <- ggplot()+
  #scale_color_manual(values = c("red", "blue"))+
  ggtitle("2013-2021")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1.2) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHSB_POST$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=0.47, col = "black", lty = 3, lwd = .5)+ #set to median
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.15, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.15, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.0, aes(0.09, 0.01 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+ 
  geom_text(size = 3.0, aes(0.89, 0.01,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
    geom_text(size = 3.0, aes(0.48, 0.01 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T) # set to quantile(LHSB_POST$FM,.50, na.rm=T) + .01



for(i in 1:nrow(LHSB_POST)){
    if(is.na(LHSB_POST$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Barred Sand Bass"

KBPars@Linf <- LHSB_POST$Linf[i]
KBPars@L50 <- LHSB_POST$L50[i]
KBPars@L95 <- LHSB_POST$L95[i]
KBPars@MK <- LHSB_POST$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 377.98 #SB_Post_Sel50[3]
KBPars@SL95 <- 410.75 #SB_Post_Sel95[3]
KBPars@BinWidth <- 10 
KBPars@FM <- LHSB_POST$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_SandBass_2013_2021_curve <- LBSPRsim(KBPars)

curves <- calcCurves(MySim_SandBass_2013_2021_curve) #calcCurves for each set of parameter values
   
#library("dplyr")
#library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

gg.SB2013.2021 <- gg.SB2013.2021 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Sand Bass"

KBPars@Linf <- 606
KBPars@L50 <- 229
KBPars@L95 <- 241.35
KBPars@MK <- 2.4
KBPars@L_units <- "mm"
KBPars@SL50 <- 377.98 #SB_Post_Sel50[3]
KBPars@SL95 <- 410.745 #SB_Post_Sel95[3]
KBPars@BinWidth <- 10 
KBPars@FM <- 0.47 #SB_Post_FM[3]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_SandBass_2013_2021_curve_median <- LBSPRsim(KBPars)


SBcurves2013 <- calcCurves(MySim_SandBass_2013_2021_curve_median) #calcCurves for each set of parameter values
   
gg.SB2013.2021 <- gg.SB2013.2021 + geom_line(aes(x=SBcurves2013$FM, y=SBcurves2013$Yield), color ="darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=SBcurves2013$FM, y=SBcurves2013$SPR), color="darkred", alpha = 1, size = 1.5)


```
####

#Barred Sand Bass 12-Inch MSL

```{r}
q25 <- quantile(LHSB_PRE$FM,.25, na.rm=T)
q75 <- quantile(LHSB_PRE$FM,.75, na.rm=T)
dens <- density(LHSB_PRE$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)



gg.SB12 <- ggplot()+
  #scale_color_manual(values = c("red", "blue"))+
  ggtitle("12-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHSB_PRE$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
   geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=.560, col = "black", lty = 3, lwd = .5)+ #set to median
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.15, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.15, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.0, aes(0.14, 0.01 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+ #.(-.09)
  geom_text(size = 3.0, aes(0.99, 0.01,label = "75th Percentile", vjust = 1.25), check_overlap = T)+#(+.09)
    geom_text(size = 3.0, aes(0.57, 0.01 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T) 



for(i in 1:nrow(LHSB_PRE)){
    if(is.na(LHSB_PRE$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Barred Sand Bass"

KBPars@Linf <- LHSB_PRE$Linf[i]
KBPars@L50 <- LHSB_PRE$L50[i]
KBPars@L95 <- LHSB_PRE$L95[i]
KBPars@MK <- LHSB_PRE$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 305
KBPars@SL95 <- 306
KBPars@BinWidth <- 10 
KBPars@FM <- LHSB_PRE$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_SandBass_12_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_SandBass_12_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.SB12 <- gg.SB12 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}
#print(gg)
```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Sand Bass"

KBPars@Linf <- 606
KBPars@L50 <- 229
KBPars@L95 <- 241.35
KBPars@MK <- 2.4
KBPars@L_units <- "mm"
KBPars@SL50 <- 305
KBPars@SL95 <- 306
KBPars@BinWidth <- 10 
KBPars@FM <- 0.56
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_SandBass_12_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_12_curve_median@SPR#

SBcurves.12 <- calcCurves(MySim_SandBass_12_curve_median) #calcCurves for each set of parameter values
   
  gg.SB12 <- gg.SB12 +    geom_line(aes(x=SBcurves.12$FM, y=SBcurves.12$Yield), color = "darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=SBcurves.12$FM, y=SBcurves.12$SPR), color="darkred", alpha = 1, size = 1.5)

  
```


###########################
#Barred Sand Bass 14-Inch MSL
```{r}
q25 <- quantile(LHSB_PRE$FM,.25, na.rm=T)
q75 <- quantile(LHSB_PRE$FM,.75, na.rm=T)
dens <- density(LHSB_PRE$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.SB14 <- ggplot()+
  #scale_color_manual(values = c("red", "blue"))+
  ggtitle("14-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHSB_PRE$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=.560, col = "black", lty = 3, lwd = .5)+ #set to median
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.15, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.15, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.0, aes(0.14, 0.01 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+ #.(-.09)
  geom_text(size = 3.0, aes(0.99, 0.01,label = "75th Percentile", vjust = 1.25), check_overlap = T)+#(+.09)
    geom_text(size = 3.0, aes(0.57, 0.01 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T) 


for(i in 1:nrow(LHSB_PRE)){
    if(is.na(LHSB_PRE$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Barred Sand Bass"

KBPars@Linf <- LHSB_PRE$Linf[i]
KBPars@L50 <- LHSB_PRE$L50[i]
KBPars@L95 <- LHSB_PRE$L95[i]
KBPars@MK <- LHSB_PRE$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 356
KBPars@SL95 <- 357
KBPars@BinWidth <- 10 
KBPars@FM <- LHSB_PRE$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_SandBass_14_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_SandBass_14_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.SB14 <- gg.SB14 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}
#print(gg)
```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Sand Bass"

KBPars@Linf <- 606
KBPars@L50 <- 229
KBPars@L95 <- 241.35
KBPars@MK <- 2.4
KBPars@L_units <- "mm"
KBPars@SL50 <- 356
KBPars@SL95 <- 357
KBPars@BinWidth <- 10 
KBPars@FM <- 0.56
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_SandBass_14_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_14_curve_median@SPR#

curves.14 <- calcCurves(MySim_SandBass_14_curve_median) #calcCurves for each set of parameter values
   
  gg.SB14 <- gg.SB14 + geom_line(aes(x=curves.14$FM, y=curves.14$Yield), color = "darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=curves.14$FM, y=curves.14$SPR), color="darkred", alpha = 1, size = 1.5)

  
  
```

16-Inch MSL Simulation

```{r}
library("tidyr")

q25 <- quantile(LHSB_POST$FM,.25, na.rm=T)
q50 <- quantile(LHSB_POST$FM,.50, na.rm=T)
q75 <- quantile(LHSB_POST$FM,.75, na.rm=T)
dens <- density(LHSB_POST$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)



gg.SB16 <- ggplot()+
  #scale_color_manual(values = c("red", "blue"))+
  ggtitle("16-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1.2) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHSB_POST$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
 geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=0.47, col = "black", lty = 3, lwd = .5)+ #set to median
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.15, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.15, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.0, aes(0.09, 0.01 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+ 
  geom_text(size = 3.0, aes(0.89, 0.01,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
    geom_text(size = 3.0, aes(0.48, 0.01 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)


for(i in 1:nrow(LHSB_POST)){
    if(is.na(LHSB_POST$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Barred Sand Bass"

KBPars@Linf <- LHSB_POST$Linf[i]
KBPars@L50 <- LHSB_POST$L50[i]
KBPars@L95 <- LHSB_POST$L95[i]
KBPars@MK <- LHSB_POST$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 406
KBPars@SL95 <- 407
KBPars@BinWidth <- 10 
KBPars@FM <- LHSB_POST$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_SandBass_16_curve <- LBSPRsim(KBPars)

curves <- calcCurves(MySim_SandBass_16_curve) #calcCurves for each set of parameter values
   
#library("dplyr")
#library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

gg.SB16 <- gg.SB16 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Sand Bass"

KBPars@Linf <- 606
KBPars@L50 <- 229
KBPars@L95 <- 241.35
KBPars@MK <- 2.4
KBPars@L_units <- "mm"
KBPars@SL50 <- 406
KBPars@SL95 <- 407
KBPars@BinWidth <- 10 
KBPars@FM <- 0.47 #SB_Post_FM[3]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_SandBass_16_curve_median <- LBSPRsim(KBPars)


SBcurves16 <- calcCurves(MySim_SandBass_16_curve_median) #calcCurves for each set of parameter values
   
gg.SB16 <- gg.SB16 + geom_line(aes(x=SBcurves16$FM, y=SBcurves16$Yield), color ="darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=SBcurves16$FM, y=SBcurves16$SPR), color="darkred", alpha = 1, size = 1.5)


```


```{r}
BSB.curves <- ggarrange(gg.SB2004.2012, gg.SB2013.2021, gg.SB12, gg.SB14, gg.SB16, ncol = 2, nrow = 3,  common.legend = TRUE, legend = "top")

annotate_figure(BSB.curves , top = text_grob("SPR and Relative Yield Response to Varying Relative Fishing Mortality \n Barred Sand Bass", color = "black", face = "bold", size = 18))

ggsave("BSBcurvesFINAL.png", width = 16, height = 14, units = "in", dpi = 500, bg = "white")

```

