---
title: "multi curve KB"
output: html_document
date: "2023-02-27"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#2004-2012
```{r}
library("tidyr")

q25 <- quantile(LHKB_PRE$FM,.25, na.rm=T)
q50 <- quantile(LHKB_PRE$FM,.50, na.rm=T)
q75 <- quantile(LHKB_PRE$FM,.75, na.rm=T)
dens <- density(LHKB_PRE$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.KB2004.2012 <- ggplot()+
  #scale_color_manual(values = c("red", "blue"))+
  ggtitle("2004-2012")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHKB_PRE$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=1.35, col = "black", lty = 3, lwd = .5)+ #set to median
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(0.87, 0.01 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+#.96 (-.09)
  geom_text(size = 3.5, aes(1.87, 0.01,label = "75th Percentile", vjust = 1.25), check_overlap = T)+#1.78(+.09)
    geom_text(size = 3.5, aes(1.36, 0.01 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)




for(i in 1:nrow(LHKB_PRE)){
#for(i in 1:15){
    if(is.na(LHKB_PRE$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Kelp Bass"

KBPars@Linf <- LHKB_PRE$Linf[i]
KBPars@L50 <- LHKB_PRE$L50[i]
KBPars@L95 <- LHKB_PRE$L95[i]
KBPars@MK <- LHKB_PRE$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 313.38 #KB_Pre_Sel50
KBPars@SL95 <- 339.28 #KB_Pre_Sel95
KBPars@BinWidth <- 10 
KBPars@FM <- LHKB_PRE$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_KelpBass_2004_2012_curve <- LBSPRsim(KBPars)



#LHKB_PRE$SPR_12_Inch_MS_KE[i] <- MySim_KelpBass_12_KE@SPR

curves <- calcCurves(MySim_KelpBass_2004_2012_curve) #calcCurves for each set of parameter values
   
#library("dplyr")
#library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

gg.KB2004.2012 <- gg.KB2004.2012 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}
#print(gg)
```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Kelp Bass"

KBPars@Linf <- 698
KBPars@L50 <- 223
KBPars@L95 <- 238.2
KBPars@MK <- 2.647
KBPars@L_units <- "mm"
KBPars@SL50 <- 313.38
KBPars@SL95 <- 339.28
KBPars@BinWidth <- 10 
KBPars@FM <- 1.35
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_KelpBass_2004_2012_curve_median <- LBSPRsim(KBPars)
#MySim_KelpBass_12_curve_median@SPR#.373

curves2004 <- calcCurves(MySim_KelpBass_2004_2012_curve_median) #calcCurves for each set of parameter values
   
gg.KB2004.2012 <- gg.KB2004.2012 + geom_line(aes(x=curves2004$FM, y=curves2004$Yield), color ="darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=curves2004$FM, y=curves2004$SPR), color="darkred", alpha = 1, size = 1.5)

  
  #print(gg.KB2004.2012)
  

    

#setwd("/Volumes/NO NAME/LBSPR/Stoch/Stochastic/Plots")
#ggsave("KB_20042012_Curve.png", width = 30, height = 20, units = "cm", dpi = 500)
```


#2013-2021

```{r}
q25 <- quantile(LHKB_POST$FM,.25, na.rm=T)
q50 <- quantile(LHKB_POST$FM,.50, na.rm=T)
q75 <- quantile(LHKB_POST$FM,.75, na.rm=T)
dens <- density(LHKB_POST$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.KB2013 <- ggplot()+
  #scale_color_manual(values = c("red", "blue"))+
  ggtitle("2013-2021")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHKB_POST$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=1.60, col = "black", lty = 3, lwd = .5)+
  #geom_vline(xintercept=c(.96, 1.78), col = "black", lty = 3, lwd = .5)+
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.00, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.00, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(1.07, 0.01 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.2, 0.01,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
    geom_text(size = 3.5, aes(1.61, 0.01 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)


for(i in 1:nrow(LHKB_POST)){
#for(i in 1:15){
    if(is.na(LHKB_POST$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Kelp Bass"

KBPars@Linf <- LHKB_POST$Linf[i]
KBPars@L50 <- LHKB_POST$L50[i]
KBPars@L95 <- LHKB_POST$L95[i]
KBPars@MK <- LHKB_POST$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 360.11
KBPars@SL95 <- 392.81
KBPars@BinWidth <- 10 
KBPars@FM <- LHKB_POST$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_KelpBass_2013_2021_curve <- LBSPRsim(KBPars)



#LHKB_PRE$SPR_16_Inch_MS_KE[i] <- MySim_KelpBass_16_KE@SPR

curves <- calcCurves(MySim_KelpBass_2013_2021_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

gg.KB2013 <- gg.KB2013 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}
#print(gg)
```

```{r}
library(ggridges)
#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Kelp Bass"

KBPars@Linf <- 698
KBPars@L50 <- 223
KBPars@L95 <- 238.2
KBPars@MK <- 2.647
KBPars@L_units <- "mm"
KBPars@SL50 <- 360.11
KBPars@SL95 <- 392.81
KBPars@BinWidth <- 10 
KBPars@FM <- 1.60
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_KelpBass_2013_2021_curve_median <- LBSPRsim(KBPars)
#MySim_KelpBass_14_curve_median@SPR#.373

curves2013 <- calcCurves(MySim_KelpBass_2013_2021_curve_median) #calcCurves for each set of parameter values
   
gg.KB2013 <- gg.KB2013 + geom_line(aes(x=curves2013$FM, y=curves2013$Yield), color = "darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=curves2013$FM, y=curves2013$SPR), color="darkred", alpha = 1, size = 1.5)
  

#print(gg.KB2013)

#setwd("/Volumes/NO NAME/LBSPR/Stoch/Stochastic/Plots")
#ggsave("KB_2013-2021_Curve.png", width = 30, height = 20, units = "cm", dpi = 500)
```












###Kelp Bass
#12 Inch MSL


```{r}
q25 <- quantile(LHKB_PRE$FM,.25, na.rm=T)
q75 <- quantile(LHKB_PRE$FM,.75, na.rm=T)
dens <- density(LHKB_PRE$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.KB12 <- ggplot()+
  #scale_color_manual(values = c("red", "blue"))+
  ggtitle("12-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHKB_PRE$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=1.35, col = "black", lty = 3, lwd = .5)+
  #geom_vline(xintercept=c(.96, 1.78), col = "black", lty = 3, lwd = .5)+
   geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(0.87, 0.01 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(1.87, 0.01,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
 # geom_text(size = 3, aes(1.35, 0.05, label = "Median", vjust = 1.5), check_overlap = T, angle = 90) #move slightly off median so vline doesnt ovelap text
    geom_text(size = 3.5, aes(1.36, 0.01 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)




for(i in 1:nrow(LHKB_PRE)){
#for(i in 1:15){
    if(is.na(LHKB_PRE$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Kelp Bass"

KBPars@Linf <- LHKB_PRE$Linf[i]
KBPars@L50 <- LHKB_PRE$L50[i]
KBPars@L95 <- LHKB_PRE$L95[i]
KBPars@MK <- LHKB_PRE$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 305
KBPars@SL95 <- 306
KBPars@BinWidth <- 10 
KBPars@FM <- LHKB_PRE$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_KelpBass_12_curve <- LBSPRsim(KBPars)



#LHKB_PRE$SPR_12_Inch_MS_KE[i] <- MySim_KelpBass_12_KE@SPR

curves <- calcCurves(MySim_KelpBass_12_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.KB12 <- gg.KB12 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}
#print(gg)
```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Kelp Bass"

KBPars@Linf <- 698
KBPars@L50 <- 223
KBPars@L95 <- 238.2
KBPars@MK <- 2.647
KBPars@L_units <- "mm"
KBPars@SL50 <- 305
KBPars@SL95 <- 306
KBPars@BinWidth <- 10 
KBPars@FM <- 1.35
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_KelpBass_12_curve_median <- LBSPRsim(KBPars)
#MySim_KelpBass_12_curve_median@SPR#.373

curves12 <- calcCurves(MySim_KelpBass_12_curve_median) #calcCurves for each set of parameter values
   
  gg.KB12 <- gg.KB12 + geom_line(aes(x=curves12$FM, y=curves12$Yield), color ="darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=curves12$FM, y=curves12$SPR), color="darkred", alpha = 1, size = 1.5)

  
  #print(gg.KB12)
  

    
#print(gg.KB12)

#setwd("/Volumes/NO NAME/LBSPR/Stoch/Stochastic/Plots")
#ggsave("KB_12MSL_Curve.png", width = 30, height = 20, units = "cm", dpi = 500)
```


####14 Inch MSL



```{r}
q25 <- quantile(LHKB_PRE$FM,.25, na.rm=T)
q75 <- quantile(LHKB_PRE$FM,.75, na.rm=T)
dens <- density(LHKB_PRE$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.KB14 <- ggplot()+
  #scale_color_manual(values = c("red", "blue"))+
  ggtitle("14-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHKB_PRE$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  	geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=1.35, col = "black", lty = 3, lwd = .5)+
  #geom_vline(xintercept=c(.96, 1.78), col = "black", lty = 3, lwd = .5)+
   geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(0.87, 0.01 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(1.87, 0.01 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
  #geom_text(size = 3, aes(1.35, 0.05 ,label = "Median", vjust = 1.5), check_overlap = T, angle = 90) #move slightly off median so vline doesnt ovelap text
      geom_text(size = 3.5, aes(1.36, 0.01 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)


for(i in 1:nrow(LHKB_PRE)){
#for(i in 1:15){
    if(is.na(LHKB_PRE$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Kelp Bass"

KBPars@Linf <- LHKB_PRE$Linf[i]
KBPars@L50 <- LHKB_PRE$L50[i]
KBPars@L95 <- LHKB_PRE$L95[i]
KBPars@MK <- LHKB_PRE$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 356
KBPars@SL95 <- 357
KBPars@BinWidth <- 10 
KBPars@FM <- LHKB_PRE$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_KelpBass_14_curve <- LBSPRsim(KBPars)



#LHKB_PRE$SPR_14_Inch_MS_KE[i] <- MySim_KelpBass_12_KE@SPR

curves <- calcCurves(MySim_KelpBass_14_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.KB14 <- gg.KB14 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}
#print(gg)
```

```{r}
library(ggridges)
#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Kelp Bass"

KBPars@Linf <- 698
KBPars@L50 <- 223
KBPars@L95 <- 238.2
KBPars@MK <- 2.647
KBPars@L_units <- "mm"
KBPars@SL50 <- 356
KBPars@SL95 <- 357
KBPars@BinWidth <- 10 
KBPars@FM <- 1.35
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_KelpBass_14_curve_median <- LBSPRsim(KBPars)
#MySim_KelpBass_14_curve_median@SPR#.373

curves14 <- calcCurves(MySim_KelpBass_14_curve_median) #calcCurves for each set of parameter values
   
  gg.KB14 <- gg.KB14 + geom_line(aes(x=curves14$FM, y=curves14$Yield), color = "darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=curves14$FM, y=curves14$SPR), color="darkred", alpha = 1, size = 1.5)
  
  
   

    
#print(gg.KB14)

#setwd("/Volumes/NO NAME/LBSPR/Stoch/Stochastic/Plots")
#ggsave("KB_14MSL_Curve.png", width = 30, height = 20, units = "cm", dpi = 500)
```


##16-Inch MSL

```{r}
q25 <- quantile(LHKB_POST$FM,.25, na.rm=T)
q75 <- quantile(LHKB_POST$FM,.75, na.rm=T)
dens <- density(LHKB_POST$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.KB16 <- ggplot()+
  #scale_color_manual(values = c("red", "blue"))+
  ggtitle("16-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHKB_POST$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  	geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=1.60, col = "black", lty = 3, lwd = .5)+
  #geom_vline(xintercept=c(.96, 1.78), col = "black", lty = 3, lwd = .5)+
  geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(1.07, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.20, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
  #geom_text(size = 3, aes(1.60, 0.05, label = "Median", vjust = 1.5), check_overlap = T, angle = 90) #move slightly off median so vline doesnt ovelap text
        geom_text(size = 3.5, aes(1.61, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)


for(i in 1:nrow(LHKB_POST)){
#for(i in 1:15){
    if(is.na(LHKB_POST$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Kelp Bass"

KBPars@Linf <- LHKB_POST$Linf[i]
KBPars@L50 <- LHKB_POST$L50[i]
KBPars@L95 <- LHKB_POST$L95[i]
KBPars@MK <- LHKB_POST$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 406
KBPars@SL95 <- 407
KBPars@BinWidth <- 10 
KBPars@FM <- LHKB_POST$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_KelpBass_16_curve <- LBSPRsim(KBPars)



#LHKB_PRE$SPR_16_Inch_MS_KE[i] <- MySim_KelpBass_16_KE@SPR

curves <- calcCurves(MySim_KelpBass_16_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.KB16 <- gg.KB16 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}
#print(gg)
```

```{r}
library(ggridges)
#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Kelp Bass"

KBPars@Linf <- 698
KBPars@L50 <- 223
KBPars@L95 <- 238.2
KBPars@MK <- 2.647
KBPars@L_units <- "mm"
KBPars@SL50 <- 406
KBPars@SL95 <- 407
KBPars@BinWidth <- 10 
KBPars@FM <- 1.60
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_KelpBass_16_curve_median <- LBSPRsim(KBPars)
#MySim_KelpBass_14_curve_median@SPR#.373

curves16 <- calcCurves(MySim_KelpBass_16_curve_median) #calcCurves for each set of parameter values
   
  gg.KB16 <- gg.KB16 + geom_line(aes(x=curves16$FM, y=curves16$Yield), color = "darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=curves16$FM, y=curves16$SPR), color="darkred", alpha = 1, size = 1.5)
  

#setwd("/Volumes/NO NAME/LBSPR/Stoch/Stochastic/Plots")
#ggsave("KB_16MSL_Curve.png", width = 30, height = 20, units = "cm", dpi = 500)
```






```{r}
KB.curves4 <- ggarrange(gg.KB2004.2012, gg.KB2013,  gg.KB12, gg.KB14, gg.KB16, ncol = 2, nrow = 3,  common.legend = TRUE, legend = "top")

annotate_figure(KB.curves4 , top = text_grob("SPR and Relative Yield Response to Varying Relative Fishing Mortality \n Kelp Bass", color = "black", face = "bold", size = 18))

ggsave("KBcurvesFINAL.png", width = 16, height = 14, units = "in", dpi = 500, bg = "white")

```
