---
title: "Olive Rockfish Curve"
output: html_document
date: "2023-02-03"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



##Olive Rockfish
## 2004-2021

```{r}
q25 <- quantile(LHOliveRFCV1$FM,.25, na.rm=T)
q75 <- quantile(LHOliveRFCV1$FM,.75, na.rm=T)
dens <- density(LHOliveRFCV1$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.Olive2004_2021 <- ggplot()+
 # scale_color_manual(values = c("red", "blue"))+
  ggtitle("2004-2021")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHOliveRFCV1$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=0.63, col = "black", lty = 3, lwd = .5)+ #median
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(0.18, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(1.10, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
      geom_text(size = 3.5, aes(0.64, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)


for(i in 1:nrow(LHOliveRFCV1)){
    if(is.na(LHOliveRFCV1$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- LHOliveRFCV1$Linf[i]
KBPars@L50 <- LHOliveRFCV1$L50[i]
KBPars@L95 <- LHOliveRFCV1$L95[i]
KBPars@MK <- LHOliveRFCV1$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <-  275.05
KBPars@SL95 <- 339.570
KBPars@BinWidth <- 10 
KBPars@FM <- LHOliveRFCV1$FM[i]
KBPars@BinMax <- 800
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.Olive2004_2021 <- gg.Olive2004_2021 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- 489.5
KBPars@L50 <- 340
KBPars@L95 <- 385
KBPars@MK <- 1.08
KBPars@L_units <- "mm"
KBPars@SL50 <- 275.05
KBPars@SL95 <- 339.570
KBPars@BinWidth <- 10 
KBPars@FM <- 0.63
KBPars@BinMax <- 800
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_curve_median <- LBSPRsim(KBPars)
#MySim_curve_median@SPR #.435

Olivecurves.2004_2023 <- calcCurves(MySim_curve_median) #calcCurves for each set of parameter values
   
  gg.Olive2004_2021 <- gg.Olive2004_2021 + geom_line(aes(x=Olivecurves.2004_2023$FM, y=Olivecurves.2004_2023$Yield), color = "darkblue", alpha = 1, size= 1.5)+
  geom_line(aes(x=Olivecurves.2004_2023$FM, y=Olivecurves.2004_2023$SPR), color="darkred", alpha = 1, size = 1.5)
  

```



###
###12-Inch MSL
```{r}
q25 <- quantile(LHOliveRFCV1$FM,.25, na.rm=T)
q75 <- quantile(LHOliveRFCV1$FM,.75, na.rm=T)
dens <- density(LHOliveRFCV1$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.Olive12 <- ggplot()+
 # scale_color_manual(values = c("red", "blue"))+
  ggtitle("12-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHOliveRFCV1$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=0.63, col = "black", lty = 3, lwd = .5)+ #median
   geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(0.18, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(1.10, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
      geom_text(size = 3.5, aes(0.64, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)



for(i in 1:nrow(LHOliveRFCV1)){
    if(is.na(LHOliveRFCV1$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- LHOliveRFCV1$Linf[i]
KBPars@L50 <- LHOliveRFCV1$L50[i]
KBPars@L95 <- LHOliveRFCV1$L95[i]
KBPars@MK <- LHOliveRFCV1$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <-  305
KBPars@SL95 <- 306
KBPars@BinWidth <- 10 
KBPars@FM <- LHOliveRFCV1$FM[i]
KBPars@BinMax <- 800
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.Olive12 <- gg.Olive12 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- 489.5
KBPars@L50 <- 340
KBPars@L95 <- 385
KBPars@MK <- 1.08
KBPars@L_units <- "mm"
KBPars@SL50 <- 305
KBPars@SL95 <- 306
KBPars@BinWidth <- 10 
KBPars@FM <- 0.63
KBPars@BinMax <- 800
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_12_curve_median@SPR#

Olivecurves.12 <- calcCurves(MySim_curve_median) #calcCurves for each set of parameter values
   
  gg.Olive12 <- gg.Olive12 + geom_line(aes(x=Olivecurves.12$FM, y=Olivecurves.12$Yield), color = "darkblue", alpha = 1, size= 1.5)+
  geom_line(aes(x=Olivecurves.12$FM, y=Olivecurves.12$SPR), color="darkred", alpha = 1, size = 1.5)
  

```



######
#14-inch MSL
```{r}
q25 <- quantile(LHOliveRFCV1$FM,.25, na.rm=T)
q75 <- quantile(LHOliveRFCV1$FM,.75, na.rm=T)
dens <- density(LHOliveRFCV1$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.Olive14 <- ggplot()+
 # scale_color_manual(values = c("red", "blue"))+
  ggtitle("14-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHOliveRFCV1$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=0.63, col = "black", lty = 3, lwd = .5)+ #median
   geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(0.18, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(1.10, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
      geom_text(size = 3.5, aes(0.64, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)



for(i in 1:nrow(LHOliveRFCV1)){
    if(is.na(LHOliveRFCV1$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- LHOliveRFCV1$Linf[i]
KBPars@L50 <- LHOliveRFCV1$L50[i]
KBPars@L95 <- LHOliveRFCV1$L95[i]
KBPars@MK <- LHOliveRFCV1$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <-  356
KBPars@SL95 <- 357
KBPars@BinWidth <- 10 
KBPars@FM <- LHOliveRFCV1$FM[i]
KBPars@BinMax <- 800
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.Olive14 <- gg.Olive14 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- 489.5
KBPars@L50 <- 340
KBPars@L95 <- 385
KBPars@MK <- 1.08
KBPars@L_units <- "mm"
KBPars@SL50 <- 356
KBPars@SL95 <- 357
KBPars@BinWidth <- 10 
KBPars@FM <- 0.63
KBPars@BinMax <- 800
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_12_curve_median@SPR#

Olivecurves.14 <- calcCurves(MySim_curve_median) #calcCurves for each set of parameter values
   
  gg.Olive14 <- gg.Olive14 + geom_line(aes(x=Olivecurves.14$FM, y=Olivecurves.14$Yield), color = "darkblue", alpha = 1, size= 1.5)+
  geom_line(aes(x=Olivecurves.14$FM, y=Olivecurves.14$SPR), color="darkred", alpha = 1, size = 1.5)
  
  
```






###16-Inch MSL
```{r}
q25 <- quantile(LHOliveRFCV1$FM,.25, na.rm=T)
q75 <- quantile(LHOliveRFCV1$FM,.75, na.rm=T)
dens <- density(LHOliveRFCV1$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.Olive16 <- ggplot()+
 # scale_color_manual(values = c("red", "blue"))+
  ggtitle("16-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHOliveRFCV1$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=0.63, col = "black", lty = 3, lwd = .5)+ #median
     geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(0.18, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(1.10, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
      geom_text(size = 3.5, aes(0.64, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)



for(i in 1:nrow(LHOliveRFCV1)){
    if(is.na(LHOliveRFCV1$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- LHOliveRFCV1$Linf[i]
KBPars@L50 <- LHOliveRFCV1$L50[i]
KBPars@L95 <- LHOliveRFCV1$L95[i]
KBPars@MK <- LHOliveRFCV1$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <-  406
KBPars@SL95 <- 407
KBPars@BinWidth <- 10 
KBPars@FM <- LHOliveRFCV1$FM[i]
KBPars@BinMax <- 800
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.Olive16 <- gg.Olive16 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Olive Rockfish"

KBPars@Linf <- 489.5
KBPars@L50 <- 340
KBPars@L95 <- 385
KBPars@MK <- 1.08
KBPars@L_units <- "mm"
KBPars@SL50 <- 406
KBPars@SL95 <- 407
KBPars@BinWidth <- 10 
KBPars@FM <- 0.63
KBPars@BinMax <- 800
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_12_curve_median@SPR#

Olivecurves.16 <- calcCurves(MySim_curve_median) #calcCurves for each set of parameter values
   
  gg.Olive16 <- gg.Olive16 +  geom_line(aes(x=Olivecurves.16 $FM, y=Olivecurves.16 $Yield), color = "darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=Olivecurves.16 $FM, y=Olivecurves.16 $SPR), color="darkred", alpha = 1, size = 1.5)

  

```


```{r}
Olive.curves <- ggarrange(gg.Olive2004_2021, gg.Olive12, gg.Olive14, gg.Olive16, ncol = 2, nrow = 2, common.legend = TRUE, legend = "top")

annotate_figure(Olive.curves, top = text_grob("SPR and Relative Yield Response to Varying Relative Fishing Mortality \n Olive Rockfish", color = "black", face = "bold", size = 18))

ggsave("OlivecurvesFINAL.png", width = 16, height = 14, units = "in", dpi = 500, bg = "white")

```

