---
title: "Multi Curve OWF"
output: pdf_document
date: "2023-03-15"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###2004-2021
```{r}
q25 <- quantile(LHOWF$FM,.25, na.rm=T)
q75 <- quantile(LHOWF$FM,.75, na.rm=T)
dens <- density(LHOWF$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.OWF2004_2021 <- ggplot()+
 # scale_color_manual(values = c("red", "blue"))+
  ggtitle("2004-2021")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHOWF$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=2.07, col = "black", lty = 3, lwd = .5)+ #median
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(1.508, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.710, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.08, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)


for(i in 1:nrow(LHOWF)){
    if(is.na(LHOWF$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- LHOWF$Linf[i]
KBPars@L50 <- LHOWF$L50[i]
KBPars@L95 <- LHOWF$L95[i]
KBPars@MK <- LHOWF$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <-  256.61
KBPars@SL95 <- 303.46
KBPars@BinWidth <- 10 
KBPars@FM <- LHOWF$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_NOMSL_curve <- LBSPRsim(KBPars)



curves <- calcCurves(MySim_OWF_NOMSL_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.OWF2004_2021 <- gg.OWF2004_2021 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          
}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- 779
KBPars@L50 <- 430
KBPars@L95 <- 513
KBPars@MK <- 1.787
KBPars@L_units <- "mm"
KBPars@SL50 <- 256.61
KBPars@SL95 <- 303.46
KBPars@BinWidth <- 10 
KBPars@FM <- 2.07
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_NOMSL_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_12_curve_median@SPR#

OWFcurves2004 <- calcCurves(MySim_OWF_NOMSL_curve_median) #calcCurves for each set of parameter values
   
  gg.OWF2004_2021 <- gg.OWF2004_2021 + geom_line(aes(x=OWFcurves2004$FM, y=OWFcurves2004$Yield), color = "darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=OWFcurves2004$FM, y=OWFcurves2004$SPR), color="darkred", alpha = 1, size = 1.5)
  

```





##############
#Ocean Whitefish 12-Inch MSL

```{r}
q25 <- quantile(LHOWF$FM,.25, na.rm=T)
q75 <- quantile(LHOWF$FM,.75, na.rm=T)
dens <- density(LHOWF$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.OWF_12 <- ggplot()+
 # scale_color_manual(values = c("red", "blue"))+
  ggtitle("12-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHOWF$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=2.07, col = "black", lty = 3, lwd = .5)+ #median
  #geom_vline(xintercept=c(.96, 1.78), col = "black", lty = 3, lwd = .5)+
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(1.508, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.710, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.08, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)




for(i in 1:nrow(LHOWF)){
    if(is.na(LHOWF$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- LHOWF$Linf[i]
KBPars@L50 <- LHOWF$L50[i]
KBPars@L95 <- LHOWF$L95[i]
KBPars@MK <- LHOWF$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 305
KBPars@SL95 <- 306
KBPars@BinWidth <- 10 
KBPars@FM <- LHOWF$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_12_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_OWF_12_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.OWF_12 <- gg.OWF_12 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}
#print(gg)
```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- 779
KBPars@L50 <- 430
KBPars@L95 <- 513
KBPars@MK <- 1.787
KBPars@L_units <- "mm"
KBPars@SL50 <- 305
KBPars@SL95 <- 306
KBPars@BinWidth <- 10 
KBPars@FM <- 2.07
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_12_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_12_curve_median@SPR#

OWFcurves.12 <- calcCurves(MySim_OWF_12_curve_median) #calcCurves for each set of parameter values
   
  gg.OWF_12 <- gg.OWF_12 +  geom_line(aes(x=OWFcurves.12$FM, y=curves.12$Yield), color = "darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=OWFcurves.12$FM, y=OWFcurves.12$SPR), color="darkred", alpha = 1, size = 1.5)

  
  

```




######
###14-inch MSL

```{r}
q25 <- quantile(LHOWF$FM,.25, na.rm=T)
q75 <- quantile(LHOWF$FM,.75, na.rm=T)
dens <- density(LHOWF$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.OWF_14 <- ggplot()+
 # scale_color_manual(values = c("red", "blue"))+
  ggtitle("14-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHOWF$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=2.07, col = "black", lty = 3, lwd = .5)+ #median
   geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(1.508, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.710, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.08, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)




for(i in 1:nrow(LHOWF)){
    if(is.na(LHOWF$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- LHOWF$Linf[i]
KBPars@L50 <- LHOWF$L50[i]
KBPars@L95 <- LHOWF$L95[i]
KBPars@MK <- LHOWF$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 356
KBPars@SL95 <- 357
KBPars@BinWidth <- 10 
KBPars@FM <- LHOWF$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_14_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_OWF_14_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.OWF_14 <- gg.OWF_14 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- 779
KBPars@L50 <- 430
KBPars@L95 <- 513
KBPars@MK <- 1.787
KBPars@L_units <- "mm"
KBPars@SL50 <- 356
KBPars@SL95 <- 357
KBPars@BinWidth <- 10 
KBPars@FM <- 2.07
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_14_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_14_curve_median@SPR#

OWFcurves.14 <- calcCurves(MySim_OWF_14_curve_median) #calcCurves for each set of parameter values
   
  gg.OWF_14 <- gg.OWF_14 + geom_line(aes(x=OWFcurves.14$FM, y=OWFcurves.14$Yield), color = "darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=OWFcurves.14$FM, y=OWFcurves.14$SPR), color="darkred", alpha = 1, size = 1.5)
  
  


```

#####
###16-inch MSL

```{r}
q25 <- quantile(LHOWF$FM,.25, na.rm=T)
q75 <- quantile(LHOWF$FM,.75, na.rm=T)
dens <- density(LHOWF$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.OWF_16 <- ggplot()+
 # scale_color_manual(values = c("red", "blue"))+
  ggtitle("16-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHOWF$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=2.07, col = "black", lty = 3, lwd = .5)+ #median
    geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(1.508, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.710, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.08, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)




for(i in 1:nrow(LHOWF)){
    if(is.na(LHOWF$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- LHOWF$Linf[i]
KBPars@L50 <- LHOWF$L50[i]
KBPars@L95 <- LHOWF$L95[i]
KBPars@MK <- LHOWF$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 406
KBPars@SL95 <- 407
KBPars@BinWidth <- 10 
KBPars@FM <- LHOWF$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_16_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_OWF_16_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.OWF_16 <- gg.OWF_16 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- 779
KBPars@L50 <- 430
KBPars@L95 <- 513
KBPars@MK <- 1.787
KBPars@L_units <- "mm"
KBPars@SL50 <- 406
KBPars@SL95 <- 407
KBPars@BinWidth <- 10 
KBPars@FM <- 2.07
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_16_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_16_curve_median@SPR#

OWFcurves.16 <- calcCurves(MySim_OWF_16_curve_median) #calcCurves for each set of parameter values
   
  gg.OWF_16 <- gg.OWF_16 +  geom_line(aes(x=OWFcurves.16$FM, y=OWFcurves.16$Yield), color = "darkblue", alpha = 1, size= 1.5)+
    geom_line(aes(x=OWFcurves.16$FM, y=OWFcurves.16$SPR), color="darkred", alpha = 1, size = 1.5)

```


###18-inch MSL

```{r}
q25 <- quantile(LHOWF$FM,.25, na.rm=T)
q75 <- quantile(LHOWF$FM,.75, na.rm=T)
dens <- density(LHOWF$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.OWF_18 <- ggplot()+
 # scale_color_manual(values = c("red", "blue"))+
  ggtitle("18-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHOWF$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=2.07, col = "black", lty = 3, lwd = .5)+ #median
   geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(1.508, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.710, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.08, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)



for(i in 1:nrow(LHOWF)){
    if(is.na(LHOWF$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- LHOWF$Linf[i]
KBPars@L50 <- LHOWF$L50[i]
KBPars@L95 <- LHOWF$L95[i]
KBPars@MK <- LHOWF$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 457
KBPars@SL95 <- 458
KBPars@BinWidth <- 10 
KBPars@FM <- LHOWF$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_18_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_OWF_18_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.OWF_18 <- gg.OWF_18 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- 779
KBPars@L50 <- 430
KBPars@L95 <- 513
KBPars@MK <- 1.787
KBPars@L_units <- "mm"
KBPars@SL50 <- 457
KBPars@SL95 <- 458
KBPars@BinWidth <- 10 
KBPars@FM <- 2.07
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_18_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_16_curve_median@SPR#

OWFcurves.18 <- calcCurves(MySim_OWF_18_curve_median) #calcCurves for each set of parameter values
   
  gg.OWF_18 <- gg.OWF_18 + geom_line(aes(x=OWFcurves.18 $FM, y=OWFcurves.18 $Yield), color = "darkblue", alpha = 1, size= 1.5)+
  geom_line(aes(x=OWFcurves.18 $FM, y=OWFcurves.18 $SPR), color="darkred", alpha = 1, size = 1.5)

```


####

###20 Inch MSL

```{r}
q25 <- quantile(LHOWF$FM,.25, na.rm=T)
q75 <- quantile(LHOWF$FM,.75, na.rm=T)
dens <- density(LHOWF$FM, na.rm = T)
df.dens <- data.frame(x = dens$x, y = dens$y)


gg.OWF_20 <- ggplot()+
 # scale_color_manual(values = c("red", "blue"))+
  ggtitle("20-Inch MSL Simulation")+
  ylab("Proportion")+
  xlab("Relative Fishing Mortality \n(F/M)")+
  theme_bw()+
  guides(color=guide_legend(title=""))+
theme(plot.title = element_text(size = 16, face = "bold", hjust = .5),
  axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"), 
		  legend.position="top", legend.text=element_text(size=12)) +
		  ggplot2::ylim(0, 1) + 
		    #ggplot2::xlim(0, 4)+ #changing limits messes up the density distribution
  coord_cartesian(xlim=c(0, 4))+
  scale_color_manual(labels = c('SPR', 'Relative Yield'), values = c("red", "blue"))+
  geom_density(aes(x=LHOWF$FM, fill = "F/M Density Distribution"), alpha = .2, color = "grey")+
  labs(fill='')+
  scale_fill_manual(values = c("grey"))+
  geom_area(data = subset(df.dens, x >= q25 & x <= q75), 
              aes(x=x,y=y), fill = 'grey', alpha = .4)+
  geom_hline(yintercept=c(0.40,0.20),col=c("darkgreen","red"),lty=2,lwd=.5)+
  geom_vline(xintercept=2.07, col = "black", lty = 3, lwd = .5)+ #median
   geom_text(size = 4, aes(0.05, .20 ,label = "20%", hjust = 1.0, vjust=-1), check_overlap = T)+ #label horizontal line at 20% SPR
  geom_text(size = 4, aes(0.05, .40 ,label = "40%", hjust = 1.0, vjust = -1), check_overlap = T)+ #label horizontal line at 40% SPR
  geom_text(size = 3.5, aes(1.508, 0 ,label = "25th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.710, 0 ,label = "75th Percentile", vjust = 1.25), check_overlap = T)+
  geom_text(size = 3.5, aes(2.08, 0 ,label = "Median", vjust = 1.25, fontface="bold"), check_overlap = T)




for(i in 1:nrow(LHOWF)){
    if(is.na(LHOWF$FM[i])){
    next #Skip lines with FM = NA
      }
    #for each value of FM, put into sim
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- LHOWF$Linf[i]
KBPars@L50 <- LHOWF$L50[i]
KBPars@L95 <- LHOWF$L95[i]
KBPars@MK <- LHOWF$M_k[i]
KBPars@L_units <- "mm"
KBPars@SL50 <- 508
KBPars@SL95 <- 509
KBPars@BinWidth <- 10 
KBPars@FM <- LHOWF$FM[i]
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_20_curve <- LBSPRsim(KBPars)





curves <- calcCurves(MySim_OWF_20_curve) #calcCurves for each set of parameter values
   
library("tidyverse")
curves2 <- curves %>%
  select(FM, SPR, Yield) %>%
  gather(key = "variable", value = "value", -FM)

  gg.OWF_20 <- gg.OWF_20 + geom_line(aes_q(x=curves2$FM, y=curves2$value, color = curves2$variable), alpha = .05)
          

}

```

```{r}

#add prior lines
KBPars <- new("LB_pars")
KBPars@Species <- "Ocean Whitefish"

KBPars@Linf <- 779
KBPars@L50 <- 430
KBPars@L95 <- 513
KBPars@MK <- 1.787
KBPars@L_units <- "mm"
KBPars@SL50 <- 508
KBPars@SL95 <- 509
KBPars@BinWidth <- 10 
KBPars@FM <- 2.07
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"

MySim_OWF_20_curve_median <- LBSPRsim(KBPars)
#MySim_SandBass_16_curve_median@SPR#

OWFcurves.20 <- calcCurves(MySim_OWF_20_curve_median) #calcCurves for each set of parameter values
   
  gg.OWF_20 <- gg.OWF_20 + geom_line(aes(x=OWFcurves.20$FM, y=OWFcurves.20$Yield), color = "darkblue", alpha = 1, size= 1.5)+
  geom_line(aes(x=OWFcurves.20$FM, y=OWFcurves.20$SPR), color="darkred", alpha = 1, size = 1.5)


```



```{r}
OWF.curves <- ggarrange(gg.OWF2004_2021, gg.OWF_12, gg.OWF_14, gg.OWF_16, gg.OWF_18, gg.OWF_20, ncol = 2, nrow = 3, common.legend = TRUE, legend = "top")

annotate_figure(OWF.curves , top = text_grob("SPR and Relative Yield Response to Varying Relative Fishing Mortality \n Ocean Whitefish", color = "black", face = "bold", size = 18))

ggsave("OWFcurvesFINAL2.png", width = 16, height = 14, units = "in", dpi = 500, bg = "white")

```
