---
title: "Pacific Barracuda Stochastic Size Limit Plots"
output: pdf_document
date: "2022-12-06"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
quantile(LHBarracuda$SPR_28_Inch_MSL_KE, probs = c(0.025,0.25,0.5,0.75,0.975), na.rm = T) #median = 0.6078366
quantile(LHBarracuda$SPR_26_Inch_MSL_KE, probs = c(0.025,0.25,0.5,0.75,0.975), na.rm = T) #median = 0.5139154

```

#this is where we can check the relative yield for our MSL Sims

##Simulate 28 inch MSL knife edge

######
Simulate 28 inch MSL with SL50 = 711 and SL95 = 712 with median SPR= 0.6078366
```{r}
KBPars <- new("LB_pars")
KBPars@Species <- "Pacific Barracuda"
#Parameters are in FL
KBPars@Linf <- 902.1
KBPars@L50 <- 465 
KBPars@L95 <- 515 
KBPars@MK <- 1.221
KBPars@L_units <- "mm"
#KBPars@fDisc <- 


KBPars@SL50 <- 711
KBPars@SL95 <- 712
KBPars@SPR <- 0.607
KBPars@BinWidth <- 20
#KBPars@FM <- 1.32
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"


MySim_Barr_28Inch_knife <- LBSPRsim(KBPars)
MySim_Barr_28Inch_knife@SPR
MySim_Barr_28Inch_knife@FM
calcCurves(MySim_Barr_28Inch_knife)
plotSim(MySim_Barr_28Inch_knife)
plotSim(MySim_Barr_28Inch_knife, type="len.freq")
plotSim(MySim_Barr_28Inch_knife, type="yield.curve")
```

density plot  
```{r}
#####
#using midpoint length bins and PLength to create data frame of density in each length bin

#MySim@LMids #size bins
#MySim@pLCatch #proportion in each bin

simulated_prop <- MySim_Barr_28Inch_knife@pLCatch[,1]
mids <- MySim_Barr_28Inch_knife@LMids

simulated_Barr_28Inch_knife <- data.frame(mids, simulated_prop)

#######
########set up bin using Binning Freq file to load in 2004-2021 data

BARR_BIN <- read.csv("~/Desktop/Organized/Data/Binned Data/Barracuda_BIN.csv")#load binned data file

newdf <- data.frame(BARR_BIN)
sum(newdf[,2])

prop <- newdf[,2]/(sum(newdf[,2]))
newdf$prop <- prop

colnames(newdf)[1] <- c("mids")

data_Barr_2004_2021 <- newdf[, c("mids", "prop")]

####
#fill by group names
data_Barr_2004_2021$name <- "data1"
simulated_Barr_28Inch_knife$name <- "simulated2"

#change names of both prop columns before binding so they match

names(data_Barr_2004_2021)[2] <- "prop"
names(simulated_Barr_28Inch_knife)[2] <- "prop"


d<- rbind(data_Barr_2004_2021, simulated_Barr_28Inch_knife)

ggplot(d, aes(x = mids, y = prop, fill=name)) + 
        geom_area(position = "dodge", linetype = 2, color = "black", alpha = .5)+ 
        ylab("Density") + 
        xlab("Length (mm)")+
        ggtitle("Change in Catch Distrubtion", "Pacific Barracuda: Simulated 28 Inch Minimum Size Limit")+
        scale_alpha_manual(values = c(`0.6` = 0.6, `1` = 1), guide = "none") + #what is this?
        theme_bw()+ #matches theme of LBSPR figures
        scale_fill_discrete(name = "Source", labels=c('CRFS 2003-2021', '28 Inch MSL Simulation'))+
  geom_vline(aes(xintercept = 711, color = "711 mm (28 inches)"), linetype = 4)+
   scale_color_manual(name = "Minimum Size Limit", values = c("711 mm (28 inches)" = "red"))

```

######
#Simulate 26 inch MSL with SL50 = 660 and SL95 = 661 with median SPR= 0.5139154
```{r}
KBPars <- new("LB_pars")
KBPars@Species <- "Pacific Barracuda"
#Parameters are in FL
KBPars@Linf <- 902.1
KBPars@L50 <- 465 
KBPars@L95 <- 515 
KBPars@MK <- 1.221
KBPars@L_units <- "mm"
#KBPars@fDisc <- 


KBPars@SL50 <- 660
KBPars@SL95 <- 661
KBPars@SPR <- 0.514
KBPars@BinWidth <- 20
#KBPars@FM <- 1.32
KBPars@BinMax <- 1500
KBPars@BinMin <- 0
KBPars@L_units <- "mm"


MySim_Barr_26Inch_knife <- LBSPRsim(KBPars)
MySim_Barr_26Inch_knife@SPR
MySim_Barr_26Inch_knife@FM
calcCurves(MySim_Barr_26Inch_knife)
plotSim(MySim_Barr_26Inch_knife)
plotSim(MySim_Barr_26Inch_knife, type="len.freq")
plotSim(MySim_Barr_26Inch_knife, type="yield.curve")
```

density plot  
```{r}
#####
#using midpoint length bins and PLength to create data frame of density in each length bin

#MySim@LMids #size bins
#MySim@pLCatch #proportion in each bin

simulated_prop <- MySim_Barr_26Inch_knife@pLCatch[,1]
mids <- MySim_Barr_26Inch_knife@LMids

simulated_Barr_26Inch_knife <- data.frame(mids, simulated_prop)

#######
#aggregate already binned
#data_Barr_2003_2021

####
#fill by group names

simulated_Barr_26Inch_knife$name <- "simulated3"

#change names of both prop columns before binding so they match

names(simulated_Barr_26Inch_knife)[2] <- "prop"



d<- rbind(data_Barr_2004_2021, simulated_Barr_26Inch_knife)

ggplot(d, aes(x = mids, y = prop, fill=name)) + 
        geom_area(position = "dodge", linetype = 2, color = "black", alpha = .5)+ 
        ylab("Density") + 
        xlab("Length (mm)")+
        ggtitle("Change in Catch Distrubtion", "Pacific Barracuda: Simulated 26 Inch Minimum Size Limit")+
        scale_alpha_manual(values = c(`0.6` = 0.6, `1` = 1), guide = "none") + #what is this?
        theme_bw()+ #matches theme of LBSPR figures
        scale_fill_discrete(name = "Source", labels=c('CRFS 2003-2021', '26 Inch MSL Simulation'))+
  geom_vline(aes(xintercept = 711, color = "711 mm (28 inches)"), linetype = 4)+
  geom_vline(aes(xintercept = 660, color = "660 mm (26 inches)"), linetype = 4)+
   scale_color_manual(name = "Minimum Size Limit", values = c("711 mm (28 inches)" = "red", "660 mm (26 inches)" = "blue"))

```

#density plot with simulated 28inch msl and 26 inch msl


density plot  
```{r}


d<- rbind(data_Barr_2004_2021, simulated_Barr_28Inch_knife, simulated_Barr_26Inch_knife)

ggplot(d, aes(x = mids, y = prop, fill=name)) + 
        geom_area(position = "dodge", linetype = 2, color = "black", alpha = .5)+ 
        ylab("Density") + 
        xlab("Length (mm)")+
        ggtitle("Change in Catch Distrubtion", "Pacific Barracuda")+
        scale_alpha_manual(values = c(`0.6` = 0.6, `1` = 1), guide = "none") + #what is this?
        theme_bw()+ #matches theme of LBSPR figures
        scale_fill_discrete(name = "Source", labels=c('CRFS 2004-2021 ', '28-Inch MSL Simulation ', '26-Inch MSL Simulation '))+
  geom_vline(aes(xintercept = 711, color = "711 mm (28 inches)"), linetype = 4)+
  geom_vline(aes(xintercept = 660, color = "660 mm (26 inches)"), linetype = 4)+
   scale_color_manual(name = "Minimum Size Limit", values = c("711 mm (28 inches)" = "blue", "660 mm (26 inches)" = "red"))+
   theme(plot.title=element_text(hjust=0.5),plot.subtitle=element_text(hjust=0.5))+
  xlim(0,1250)

#ggsave("BARR_changeindist_Stochastic.png", width = 30, height = 20, units = "cm", dpi = 500)
```
